In [3]:
from nnfs.datasets import spiral_data
import matplotlib.pyplot as plt
import numpy as np
import nnfs
nnfs.init()

In [2]:
X, y = spiral_data(samples=100, classes=3)

In [4]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [6]:
dense_1 = Layer_Dense(2, 3)
dense_1.forward(X)
print(dense_1.output[0: 3])

[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [6.8069268e-05 9.3613262e-06 1.3719607e-04]
 [1.8628142e-04 2.9210053e-06 2.1303077e-04]]
