In [12]:
import math
import numpy as np

layer_output_1 = np.array([0.7, 1.1, 0.9])
# Define E value
E = math.e

In [14]:
ex_values = []

for ouput in layer_output_1:
    ex_value = E ** ouput
    ex_values.append(ex_value)

sum_ex_values = np.sum(ex_values)

probabilities = []
for ex_value in ex_values:
    probabilities.append(ex_value / sum_ex_values)

print(probabilities)

[0.26930749917773783, 0.4017595785333555, 0.3289329222889067]


this above code cannot handle for dataset as batchs, so let's make it possible below with created as class

- Created as Class

In [62]:
class Activation_Softmax:

    # forward pass
    def forward(self, inputs):
        # calculate exponential values
        ex_values = np.exp(inputs)
        sum_ex_values = [np.sum(ex_value) for ex_value in ex_values] # option2: np.sum(ex_values, axis=1)
        self.output = [ex_value / sum_ex_value for ex_value, sum_ex_value in zip(ex_values, sum_ex_values)]

- Add Batch

In [66]:
layer_output_batch = [[0.7, 7, 0.9], 
                      [0.3, 5, 0.4], 
                      [0.2, 4, 0.1]]

softmax = Activation_Softmax()

softmax.forward(layer_output_batch)
for row in softmax.output:
    print(row)

[0.00182884 0.9959374  0.00223376]
[0.0089244  0.98121261 0.00986299]
[0.02145645 0.95912894 0.0194146 ]


- explain axis = 0, and axis = 1

In [ ]:
layer_output_batch = np.array([[0.7, 7, 0.9], 
                      [0.3, 5, 0.4], 
                      [0.2, 4, 0.1]])

output = np.sum(layer_output_batch, axis=0)
output2 = np.sum(layer_output_batch, axis=1)

print(output)
print(output2)

[1.20e+00 5.02e+03 1.40e+00]
[8.6000e+00 5.0097e+03 4.3000e+00]


In [58]:
print (np.exp( 1000 ))

inf


C:\Users\User\AppData\Local\Temp\ipykernel_13164\302018626.py:1: RuntimeWarning: overflow encountered in exp
  print (np.exp( 1000 ))


To prevent the exponential function from overflowing or large number we can use all num minus with large num

#### Update Softmax function

In [96]:
class Activation_Softmax:

    # forward pass
    def forward(self, inputs):
        # handle overflowing error
        inputs = [np.subtract(input, np.max(input)) for input in inputs]
        # calculate exponential values
        ex_values = np.exp(inputs)
        sum_ex_values = [np.sum(ex_value) for ex_value in ex_values] # option2: np.sum(ex_values, axis=1)
        self.output = [ex_value / sum_ex_value for ex_value, sum_ex_value in zip(ex_values, sum_ex_values)]

In [97]:
layer_output_batch = [[0.7, 7, 0.9], 
                      [0.3, 7, 0.4], 
                      [0.2, 4, 0.1]]

softmax = Activation_Softmax()

softmax.forward(layer_output_batch)
for row in softmax.output:
    print(row)

[0.00182884 0.9959374  0.00223376]
[0.00122773 0.99741542 0.00135685]
[0.02145645 0.95912894 0.0194146 ]
