In [1]:
from nnfs.datasets import spiral_data
import matplotlib.pyplot as plt
import numpy as np
import nnfs
nnfs.init()

In [2]:
X, y = spiral_data(samples=100, classes=3)

In [3]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [4]:
# ReLU activation
class Activation_ReLU:
    # Forward pass
    def forward ( self , inputs ):
        # Calculate output values from inputs
        self.output = np.maximum(0, inputs)

class Activation_Softmax:

    # forward pass
    def forward(self, inputs):
        # handle overflowing error
        inputs = [np.subtract(input, np.max(input)) for input in inputs]
        # calculate exponential values
        ex_values = np.exp(inputs)
        sum_ex_values = [np.sum(ex_value) for ex_value in ex_values] # option2: np.sum(ex_values, axis=1)
        self.output = [ex_value / sum_ex_value for ex_value, sum_ex_value in zip(ex_values, sum_ex_values)]

In [5]:
dense_layer_1 = Layer_Dense(2, 3)
activation_layer_1 = Activation_ReLU()
dense_layer_2 = Layer_Dense(3, 3)
activation_layer_2 = Activation_Softmax()

dense_layer_1.forward(X)
activation_layer_1.forward(dense_layer_1.output)
dense_layer_2.forward(activation_layer_1.output)
activation_layer_2.forward(dense_layer_2.output)

for output in activation_layer_2.output[0:5]:
    print(output)

[0.33333334 0.33333334 0.33333334]
[0.3333332  0.3333332  0.33333364]
[0.3333329  0.33333293 0.3333342 ]
[0.3333326  0.33333263 0.33333477]
[0.33333233 0.3333324  0.33333528]
