In [1]:
import numpy as np

In [9]:
inputs = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

weight_1 = np.array([
    [0.2, 0.8, -0.5],
    [0.5, 0.1, -0.1],
    [0.5, 0.1, -0.1]
])

weight_2 = np.array([
    [0.1, -0.1, 0.1],
    [0.1, -0.6, 0.1],
    [0.1, -0.1, 0.1]
])

bias_1 = np.array([2, 0.5, 1.5])
bias_2 = np.array([1, 1, 1])

In [10]:
output_1 = np.dot(inputs, weight_1.T) + bias_1
print(output_1)

[[2.3 0.9 1.9]
 [3.8 2.4 3.4]
 [5.3 3.9 4.9]]


In [11]:
output = np.dot(output_1, weight_2.T) + bias_2
print(output)

[[ 1.33  0.88  1.33]
 [ 1.48  0.28  1.48]
 [ 1.63 -0.32  1.63]]
